spring.datasource.url=jdbc:postgresql://postgres:5432/bank_batch

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.kafka.bootstrap-servers=kafka-1:29092,kafka-2:29092,kafka-3:29092

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authorization-server:9000/oauth2/jwks

eureka.instance.ip-address=ms-transacciones
eureka.instance.hostname=ms-transacciones