eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.security.oauth2.client.provider.bank-client.authorization-uri=http://localhost:9000/oauth2/authorize
spring.security.oauth2.client.provider.bank-client.token-uri=http://authorization-server:9000/oauth2/token
spring.security.oauth2.client.provider.bank-client.jwk-set-uri=http://authorization-server:9000/oauth2/jwks
spring.security.oauth2.client.provider.bank-client.user-info-uri=http://authorization-server:9000/userinfo
spring.security.oauth2.client.provider.bank-client.user-name-attribute=sub