spring.application.name=bff-web
server.port=8081


resilience4j.circuitbreaker.instances.cuentas.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.cuentas.slidingWindowSize=5
resilience4j.circuitbreaker.instances.cuentas.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.cuentas.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cuentas.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cuentas.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.intereses.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.intereses.slidingWindowSize=5
resilience4j.circuitbreaker.instances.intereses.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.intereses.failureRateThreshold=50
resilience4j.circuitbreaker.instances.intereses.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.intereses.permittedNumberOfCallsInHalfOpenState=2

spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=true


resilience4j.circuitbreaker.instances.transacciones.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.transacciones.slidingWindowSize=5
resilience4j.circuitbreaker.instances.transacciones.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.transacciones.failureRateThreshold=50
resilience4j.circuitbreaker.instances.transacciones.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.transacciones.permittedNumberOfCallsInHalfOpenState=2

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.oauth2.client.registration.bank-client.client-id=bank-client
spring.security.oauth2.client.registration.bank-client.client-secret=bank-secret
spring.security.oauth2.client.registration.bank-client.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.bank-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.bank-client.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.bank-client.scope=openid,profile

spring.security.oauth2.client.provider.bank-client.authorization-uri=http://localhost:9000/oauth2/authorize
spring.security.oauth2.client.provider.bank-client.token-uri=http://localhost:9000/oauth2/token
spring.security.oauth2.client.provider.bank-client.jwk-set-uri=http://localhost:9000/oauth2/jwks
spring.security.oauth2.client.provider.bank-client.user-info-uri=http://localhost:9000/userinfo
spring.security.oauth2.client.provider.bank-client.user-name-attribute=sub

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE