spring.application.name=duoc

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_batch
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.job.enabled=false