spring.application.name=bff-atm
server.port=8083

resilience4j.circuitbreaker.instances.cuentas.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.cuentas.slidingWindowSize=5
resilience4j.circuitbreaker.instances.cuentas.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.cuentas.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cuentas.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cuentas.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.intereses.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.intereses.slidingWindowSize=5
resilience4j.circuitbreaker.instances.intereses.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.intereses.failureRateThreshold=50
resilience4j.circuitbreaker.instances.intereses.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.intereses.permittedNumberOfCallsInHalfOpenState=2

spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=true